# Problem 1

In [10]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
x = np.linspace(0, 10, 5)
print(x)
# 3 - matris'in boyutunu öğrenin
print(x.shape)
# 4 - matris'i yeniden boyutlandırın
yeni = x.reshape(1,5)
# 5 - matris'in boyut sayısını öğrenin
print(yeni.ndim)

[ 0.   2.5  5.   7.5 10. ]
(5,)
2


# Problem 2

In [21]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
a = np.arange(1,10,2)
print(a)

# 2 - Oluşturduğunuz matrisi parçalayın
print(np.split(a,[2,3]))

# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([a]))

[1 3 5 7 9]
[array([1, 3]), array([5]), array([7, 9])]
[1 3 5 7 9]


# Problem 3

In [39]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
c = np.random.randint(5,100,10)
print(c)
# 2 - matris'in özelliklerini inceleyin
print(z.shape)
print(z.ndim)
print(z.dtype)
print(z.size)



[64  8 95  5 20 15 52 71 64 53]
(48,)
1
int64
48
