# Problem 1 

In [3]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([3, 1, 4, 1, 5])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
k = np.sort(array)

print("array:", array)
print("Küçükten büyüğe array:", k)

array: [3 1 4 1 5]
Küçükten büyüğe array: [1 1 3 4 5]


# Problem 2

In [2]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
dizi1 = np.array([10, 15, 30, 45, 60])
print("Dizi 1:", dizi1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
dizi2 = np.arange(5, 16)
print("Dizi 2:", dizi2)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
dizi3 = np.arange(50, 101, 5)
print("Dizi 3:", dizi3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
dizi4 = np.zeros(10)
print("Dizi 4:", dizi4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
dizi5 = np.ones(10)
print("Dizi 5:", dizi5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
dizi6 = np.linspace(0, 100, 5)
print("Dizi 6:", dizi6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
dizi7 = np.random.randint(10, 31, size=5)
print("Dizi 7:", dizi7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
dizi8 = np.random.uniform(-1, 1, size=10)
print("Dizi 8:", dizi8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris = np.random.randint(10, 51, size=(3, 5))
print("Matris:\n", matris)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız.
satir_sayisi, sutun_sayisi = matris.shape
toplam = satir_sayisi + sutun_sayisi
print("Satır ve sütun sayıları toplamı:", toplam)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
en_buyuk = np.max(matris)
en_kucuk = np.min(matris)
ortalama = np.mean(matris)
print("En büyük değer:", en_buyuk)
print("En küçük değer:", en_kucuk)
print("Ortalama değer:", ortalama)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
en_buyuk_indeks = np.argmax(matris)
print("En büyük değerin indeksi:", en_buyuk_indeks)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
dizi13 = np.arange(10, 21)
ilk_uc = dizi13[:3]
print("İlk 3 eleman:", ilk_uc)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
ters_dizi = dizi13[::-1]
print("Ters çevrilmiş dizi:", ters_dizi)

# 15- Üretilen matrisin ilk satırını seçiniz.
ilk_satir = matris[0]
print("İlk satır:", ilk_satir)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
eleman = matris[1, 2]
print("2. satır 3. sütundaki eleman:", eleman)

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
ilk_elemanlar = matris[:, 0]
print("Tüm satırlardaki ilk elemanlar:", ilk_elemanlar)

# 18- Üretilen matrisin her bir elemanının karesini alınız.
karesi = np.power(matris, 2)
print("Her bir elemanın karesi:\n", karesi)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matris_19 = np.random.randint(-50, 51, size=(3, 5))
pozitif_ciftler = matris_19[(matris_19 > 0) & (matris_19 % 2 == 0)]
print("Pozitif çift sayılar:\n", pozitif_ciftler)

Dizi 1: [10 15 30 45 60]
Dizi 2: [ 5  6  7  8  9 10 11 12 13 14 15]
Dizi 3: [ 50  55  60  65  70  75  80  85  90  95 100]
Dizi 4: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dizi 5: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Dizi 6: [  0.  25.  50.  75. 100.]
Dizi 7: [29 22 26 11 11]
Dizi 8: [-0.81695918 -0.39078015 -0.94008441  0.6912674  -0.50187954 -0.96738994
 -0.79603066 -0.58854963 -0.1402804   0.37881094]
Matris:
 [[39 15 50 33 38]
 [15 36 29 35 34]
 [10 38 33 48 18]]
Satır ve sütun sayıları toplamı: 8
En büyük değer: 50
En küçük değer: 10
Ortalama değer: 31.4
En büyük değerin indeksi: 2
İlk 3 eleman: [10 11 12]
Ters çevrilmiş dizi: [20 19 18 17 16 15 14 13 12 11 10]
İlk satır: [39 15 50 33 38]
2. satır 3. sütundaki eleman: 29
Tüm satırlardaki ilk elemanlar: [39 15 10]
Her bir elemanın karesi:
 [[1521  225 2500 1089 1444]
 [ 225 1296  841 1225 1156]
 [ 100 1444 1089 2304  324]]
Pozitif çift sayılar:
 [42 26 26]
